/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./Components/Ui/AppButton.vue')['default']
    AppFooter: typeof import('./Components/Layout/AppFooter.vue')['default']
    AppInput: typeof import('./Components/Ui/AppInput.vue')['default']
    AppLogo: typeof import('./Components/Layout/AppLogo.vue')['default']
    AppModal: typeof import('./Components/Ui/AppModal.vue')['default']
    AppNavbar: typeof import('./Components/Layout/AppNavbar.vue')['default']
    AppSidebar: typeof import('./Components/Layout/AppSidebar.vue')['default']
  }
}
